### ISSUE TITLE
I have an idea

### ISSUE THREAD

**Issue by WebShivam** [chryz-hub/web-dev-resources#10]
**Description**
Idea is to add CSS Games link
A brief description of the ideas:
I want to include website links for css games where user can Learn CSS by playing games
 
**Goals**
The aim and objectives of the ideas:
It will help and encourage more beginners to learn CSS and they'll have a good grasp over it and moreover, they'll enjoy the learning process

**Comment by chryzcode** [comment]
Yeah it is a nice idea. Please move on with that.

But you would have to  create a new category doe that under the CSS section.

**Comment by WebShivam** [comment]
Thank you so much for providing this opportunity

**Comment by chryzcode** [comment]
Yeah, and I'm happy to see your zeal in contribute to the community.
