### ISSUE TITLE
Fix the indentation

### ISSUE THREAD

**Issue by namangupta1399** [chryz-hub/web-dev-resources#21]
**Description**
Fix the indentation of child dropdowns in **README.md**.
Solution: Add some space before child dropdowns.

**Screenshots**

Please add a screenshot if applicable
![image](https://user-images.githubusercontent.com/53571307/124649263-e35e7f80-deb5-11eb-90de-27d0f087bf8b.png)

[Optional] **Additional Context**

**Comment by Mannuel25** [comment]
I tried fixing it, kindly check if it's fixed. If not, i could make some changes again.

**Comment by namangupta1399** [comment]
> I tried fixing it, kindly check if it's fixed. If not, i could make some changes again.

@Mannuel25, I have reviewed the PR, pls check https://github.com/chryz-hub/web-dev-resources/pull/24#pullrequestreview-701037677

**Comment by Mannuel25** [comment]
@namangupta1399 , kindly verify if the issue has been fixed.

**Comment by chryzcode** [comment]
#25  done already @Mannuel25
