### ISSUE TITLE
Add a frontend resource

### ISSUE THREAD

**Issue by namangupta1399** [chryz-hub/web-dev-resources#8]
**Description**

A brief description of the ideas: Add **[FrontendMentor](https://www.frontendmentor.io/)** website link

**Goals**

The aim and objectives of the ideas: Developers can work on their frontend skills through this resource.

**Comment by namangupta1399** [comment]
@chryzcodez , should I create a new section for **Frontend** since it doesn't fall under any other specific category?

**Comment by chryzcode** [comment]
Yes please do!
